GET http://localhost:3001/grades

###

GET http://localhost:3001/grades/1

###

POST  http://localhost:3001/grades
Content-Type: application/json

{
  "id": 8, 
  "name": "Issac Semhar", 
  "course": "CS577", 
  "grade": 90 
}

###
DELETE http://localhost:3001/grades/1

